name: Bump Version

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: echo 'Ran all test suites.'
      # - run: npm ci
      # - run: npm test
      # - run: npm run lint

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: 'Setting git'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Bump Version"
          git checkout $PUSH_BRANCH
          git status
      - run: npm ci
      - run: npm run build
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
