name: Bump Version

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: echo 'Ran all test suites.'
      # - run: npm ci
      # - run: npm test
      # - run: npm run lint

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: 'Set up global git config'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Bump Version"

      - run: echo "::set-env name=PUSH_BRANCH::`echo "$GITHUB_REF" | awk -F / '{ print $3 }'`"
      - run: git checkout $PUSH_BRANCH

      - name: Set up .netrc file with GitHub credentials
        run: |
          cat <<- EOF > $HOME/.netrc
          machine github.com
          login $GITHUB_ACTOR
          password $GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci
      - run: npm run build
      - run: HUSKY_SKIP_HOOKS=1 npx standard-version
      - run: git push --follow-tags origin $PUSH_BRANCH
